name: CI/CD Pipeline for app

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t ait-app -f Containerfile . --no-cache
        docker tag ait-app bollae/ait-app
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push bollae/ait-app

  run:
    name: Run docker container
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull bollae/ait-app

    - name: Run docker container
      run: |
        docker container run -d --name ait-app -p 8080:80 ait-app
